CREATE TABLE products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE people (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    favorite_product_id INT NOT NULL,
    FOREIGN KEY (favorite_product_id) REFERENCES products(id)
);

INSERT INTO products (name) VALUES ('Fotboll');
INSERT INTO products (name) VALUES ('Dator');

INSERT INTO people (name, favorite_product_id) VALUES ('Rasmus', 2);
INSERT INTO people (name, favorite_product_id) VALUES ('Kalle', 1);
